type Operation = Record<string, unknown>;

const apiError = { description: "Safe error response", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } };
const success = { description: "Successful response", content: { "application/json": { schema: { $ref: "#/components/schemas/SuccessResponse" } } } };

function operation(summary: string, access: string, requestBody?: Record<string, unknown>): Operation {
  return { summary, description: `Access: ${access}. Responses use { success, data } or { success: false, error }.`, ...(requestBody ? { requestBody } : {}), responses: { "200": success, "201": success, "400": apiError, "401": apiError, "403": apiError, "404": apiError, "422": apiError, "500": apiError } };
}

const body = (schema: string, required = true) => ({ required, content: { "application/json": { schema: { $ref: `#/components/schemas/${schema}` } } } });
const adminCollection = (name: string) => ({ get: operation(`List ${name}`, "ADMIN; query: page, limit, and q where supported"), post: operation(`Create ${name}`, "ADMIN", body("AdminMutation")) });
const adminDetail = (name: string) => ({ get: operation(`Get ${name}`, "ADMIN; path: id"), patch: operation(`Update ${name}`, "ADMIN; path: id", body("AdminMutation")), delete: operation(`Deactivate or delete ${name}`, "ADMIN; path: id") });

export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "Mahavir Card API", version: "1.0.0", description: "HTTP API for Mahavir Card. Database access stays server-side behind Next.js Route Handlers." },
  servers: [{ url: "/", description: "Current deployment" }],
  tags: [{ name: "System" }, { name: "Catalog" }, { name: "Customer" }, { name: "Admin" }, { name: "Authentication" }],
  paths: {
    "/api/health": { get: { ...operation("Health check", "Public"), tags: ["System"], responses: { "200": { description: "Service is available", content: { "application/json": { example: { success: true, data: { status: "ok" } } } } } } } },
    "/api/openapi": { get: { ...operation("OpenAPI document", "Public"), tags: ["System"] } },
    "/api/auth/{path}": { post: { ...operation("Better Auth endpoint", "Public or session-based, depending on operation"), tags: ["Authentication"], parameters: [{ name: "path", in: "path", required: true, schema: { type: "string" }, description: "Better Auth operation, for example sign-in/email or sign-in/phone-number." }] } },
    "/api/account/phone": { post: { ...operation("Attach or update a mobile number", "Authenticated CUSTOMER or ADMIN", body("PhoneInput")), tags: ["Customer"] } },
    "/api/categories": { get: { ...operation("List active categories", "Public"), tags: ["Catalog"] }, post: { ...operation("Create category", "ADMIN", body("CategoryInput")), tags: ["Admin"] } },
    "/api/categories/{id}": { get: { ...operation("Get category", "Public; path: id"), tags: ["Catalog"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/products": { get: { ...operation("List active products with server-derived starting prices", "Public; query: q, category, orderable, quoteable, page, limit. Supplying page or limit returns items and pagination metadata."), tags: ["Catalog"] }, post: { ...operation("Create product", "ADMIN", body("ProductInput")), tags: ["Admin"] } },
    "/api/products/{id}": { get: { ...operation("Get product by ID or slug with server-derived starting price", "Public; path: id"), tags: ["Catalog"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/admin/products/{id}/catalog": {
      get: { ...operation("Get complete product configuration", "ADMIN; path: id"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
      post: { ...operation("Create a product configuration resource", "ADMIN; resource may be ARTWORK_REQUIREMENT, PRICING_RULE, ADDON, DELIVERY_RULE, SECTION, or SECTION_ITEM", body("ProductCatalogMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
      patch: { ...operation("Update a product configuration resource", "ADMIN; resource and resource id are required", body("ProductCatalogMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
      delete: { ...operation("Delete a product configuration resource", "ADMIN; resource and resource id are required", body("ProductCatalogMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    },
    "/api/pricing/calculate": { post: { ...operation("Calculate server-side price", "Public", body("PricingRequest")), tags: ["Catalog"] } },
    "/api/inquiries": { get: { ...operation("List inquiries", "ADMIN"), tags: ["Admin"] }, post: { ...operation("Create inquiry", "Public", body("InquiryInput")), tags: ["Customer"] } },
    "/api/leads": { get: { ...operation("List leads", "ADMIN"), tags: ["Admin"] }, post: { ...operation("Create lead", "Public", body("InquiryInput")), tags: ["Customer"] } },
    "/api/cart": { get: { ...operation("Get a server-repriced purchase or quote basket", "Authenticated CUSTOMER; query: kind=PURCHASE or QUOTE"), tags: ["Customer"] }, delete: { ...operation("Clear a purchase or quote basket", "Authenticated CUSTOMER; query: kind=PURCHASE or QUOTE"), tags: ["Customer"] } },
    "/api/cart/items": { post: { ...operation("Add a validated product configuration to a basket", "Authenticated CUSTOMER", body("CartItemInput")), tags: ["Customer"] } },
    "/api/cart/items/{id}": { patch: { ...operation("Update basket quantity or configuration and reprice it", "Authenticated basket owner", body("CartItemUpdate")), tags: ["Customer"] }, delete: { ...operation("Remove a basket item", "Authenticated basket owner"), tags: ["Customer"] } },
    "/api/checkout": { post: { ...operation("Create an order transactionally from the authenticated purchase basket", "Authenticated CUSTOMER; all totals are recalculated server-side", body("CheckoutInput")), tags: ["Customer"] } },
    "/api/quotes": { get: { ...operation("List quotes", "Authenticated CUSTOMER owns records; ADMIN sees all"), tags: ["Customer"] }, post: { ...operation("Submit the authenticated quote basket", "Authenticated CUSTOMER", body("QuoteInput")), tags: ["Customer"] } },
    "/api/orders": { get: { ...operation("List orders", "Authenticated CUSTOMER owns records; ADMIN sees all"), tags: ["Customer"] }, post: { ...operation("Create order", "Authenticated CUSTOMER or ADMIN", body("OrderInput")), tags: ["Customer"] } },
    "/api/orders/{id}/payment": { get: { ...operation("Get order payment", "Authenticated CUSTOMER owns order; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] }, post: { ...operation("Create payment intent", "Authenticated CUSTOMER owns order; path: id", body("PaymentInput")), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/artworks": { get: { ...operation("List artworks", "Authenticated CUSTOMER owns records; ADMIN sees all"), tags: ["Customer"] } },
    "/api/artworks/upload-url": { post: { ...operation("Authorize an admin-configured private artwork upload and return a short-lived R2 PUT URL", "Authenticated CUSTOMER", body("ArtworkInput")), tags: ["Customer"] } },
    "/api/artworks/{id}/finalize": { post: { ...operation("Verify the uploaded R2 object and finalize metadata", "Authenticated CUSTOMER owns artwork; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/artworks/{id}": { get: { ...operation("Get artwork", "Authenticated CUSTOMER owns artwork; ADMIN sees all; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] }, delete: { ...operation("Remove private artwork", "Authenticated CUSTOMER owns artwork; ADMIN allowed; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/artworks/{id}/download": { get: { ...operation("Create a short-lived private artwork download", "Authenticated CUSTOMER owns artwork; ADMIN allowed; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/products/{id}/images": { get: { ...operation("List product image metadata", "Public; path: id"), tags: ["Catalog"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/categories/{id}/images": { get: { ...operation("List category image metadata", "Public; path: id"), tags: ["Catalog"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/invoices/{id}/download": { get: { ...operation("Create a short-lived invoice download", "Authenticated owner or ADMIN; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/quotes/{id}/document/download": { get: { ...operation("Create a short-lived quotation PDF download", "Authenticated quote owner or ADMIN; path: id"), tags: ["Customer"], parameters: [{ $ref: "#/components/parameters/Id" }] } },
    "/api/admin/categories": { ...adminCollection("categories"), tags: ["Admin"] },
    "/api/admin/categories/{id}": { ...adminDetail("category"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/products": { ...adminCollection("products"), tags: ["Admin"] },
    "/api/admin/products/{id}": { ...adminDetail("product"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/products/{id}/images": { get: operation("List product images", "ADMIN; path: id"), post: operation("Upload product image to R2", "ADMIN; multipart image; path: id"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/categories/{id}/images": { post: operation("Upload category image to R2", "ADMIN; multipart image; path: id"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/branding/assets": { get: operation("List branding assets", "ADMIN"), post: operation("Upload or replace branding asset in R2", "ADMIN; multipart image"), tags: ["Admin"] },
    "/api/admin/documents": { get: operation("List private documents", "ADMIN"), post: operation("Upload private PDF to R2", "ADMIN; multipart PDF"), tags: ["Admin"] },
    "/api/admin/pricing": { ...adminCollection("pricing rules"), tags: ["Admin"] },
    "/api/admin/pricing/{id}": { ...adminDetail("pricing rule"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/quotes": { get: operation("List quotes", "ADMIN; query: page, limit"), post: operation("Create quote", "ADMIN", body("QuoteInput")), tags: ["Admin"] },
    "/api/admin/quotes/{id}": { get: operation("Get quote", "ADMIN; path: id"), patch: operation("Update quote status or totals", "ADMIN; path: id", body("AdminMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/orders": { get: operation("List orders", "ADMIN; query: page, limit"), tags: ["Admin"] },
    "/api/admin/orders/{id}": { get: operation("Get order", "ADMIN; path: id"), patch: operation("Update order lifecycle", "ADMIN; path: id", body("AdminMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/payments": { get: operation("List payments", "ADMIN"), tags: ["Admin"] },
    "/api/admin/payments/{id}": { get: operation("Get payment", "ADMIN; path: id"), patch: operation("Update payment status", "ADMIN; path: id", body("AdminMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/customers": { get: operation("List customers", "ADMIN; query: page, limit, q"), tags: ["Admin"] },
    "/api/admin/customers/{id}": { get: operation("Get customer", "ADMIN; path: id"), patch: operation("Update customer", "ADMIN; path: id", body("AdminMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/artworks": { get: operation("List artworks", "ADMIN"), tags: ["Admin"] },
    "/api/admin/artworks/{id}": { get: operation("Get artwork", "ADMIN; path: id"), patch: operation("Review artwork", "ADMIN; path: id", body("AdminMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/inquiries": { get: operation("List inquiries", "ADMIN; query: page, limit, q"), tags: ["Admin"] },
    "/api/admin/inquiries/{id}": { get: operation("Get inquiry", "ADMIN; path: id"), patch: operation("Update inquiry", "ADMIN; path: id", body("AdminMutation")), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/inquiries/{id}/convert-to-quote": { post: operation("Convert inquiry to quote", "ADMIN; path: id"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
    "/api/admin/admins": { get: operation("List admins", "ADMIN"), post: operation("Create admin", "ADMIN", body("AdminInput")), tags: ["Admin"] },
    "/api/admin/admins/{id}": { get: operation("Get admin", "ADMIN; path: id"), patch: operation("Update or deactivate admin", "ADMIN; path: id", body("AdminMutation")), delete: operation("Deactivate admin", "ADMIN; path: id"), tags: ["Admin"], parameters: [{ $ref: "#/components/parameters/Id" }] },
  },
  components: {
    parameters: { Id: { name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } } },
    schemas: {
      SuccessResponse: { type: "object", required: ["success", "data"], properties: { success: { type: "boolean", const: true }, data: {} } },
      ErrorResponse: { type: "object", required: ["success", "error"], properties: { success: { type: "boolean", const: false }, error: { type: "object", properties: { code: { type: "string", enum: ["UNAUTHORIZED", "FORBIDDEN", "NOT_FOUND", "VALIDATION_ERROR", "CONFLICT", "REQUEST_ERROR", "INTERNAL_ERROR"] }, message: { type: "string" }, details: {} } } } },
      PhoneInput: { type: "object", required: ["phoneNumber"], properties: { phoneNumber: { type: "string", example: "9876543210" } } },
      CategoryInput: { type: "object", required: ["name", "slug"], properties: { name: { type: "string" }, slug: { type: "string" }, description: { type: "string" }, isActive: { type: "boolean" } } },
      ProductInput: { type: "object", required: ["name", "slug", "categoryId"], properties: { name: { type: "string" }, slug: { type: "string" }, categoryId: { type: "string", format: "uuid" }, description: { type: "string" }, configuration: { type: "object" } } },
      ProductStartingPrice: { type: "object", required: ["startingPrice", "startingQuantity", "currency", "priceLabel", "priceState", "taxInclusive"], properties: { startingPrice: { type: ["number", "null"], minimum: 0 }, startingQuantity: { type: ["integer", "null"], minimum: 1 }, currency: { type: "string", const: "INR" }, priceLabel: { type: "string", examples: ["Starts from \u20b9250 / 1,000", "Custom quote"] }, priceState: { type: "string", enum: ["STARTING", "CUSTOM_QUOTE", "CONTACT"] }, taxInclusive: { type: ["boolean", "null"] } }, description: "Derived server-side from valid active base pricing rules. Optional add-ons and delivery are excluded." },
      PricingRequest: { type: "object", required: ["productId", "quantity"], properties: { productId: { type: "string", format: "uuid" }, quantity: { type: "integer", minimum: 1 }, options: { type: "object" } } },
      InquiryInput: { type: "object", required: ["contactName", "email", "message"], properties: { contactName: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" }, message: { type: "string" } } },
      QuoteInput: { type: "object", required: ["contactName", "email"], properties: { contactName: { type: "string" }, email: { type: "string", format: "email", description: "Must match the authenticated account." }, phone: { type: "string" }, companyName: { type: "string" }, notes: { type: "string" } } },
      CartItemInput: { type: "object", required: ["kind", "productId", "quantity", "configuration"], properties: { kind: { type: "string", enum: ["PURCHASE", "QUOTE"] }, productId: { type: "string", format: "uuid" }, quantity: { type: "integer", minimum: 1 }, configuration: { type: "object", description: "Pricing rule, add-on, delivery, and owned artwork references. Values are validated server-side." } } },
      CartItemUpdate: { type: "object", required: ["quantity"], properties: { quantity: { type: "integer", minimum: 1 }, configuration: { type: "object" } } },
      CheckoutInput: { type: "object", required: ["customer", "address", "paymentMethod"], properties: { customer: { type: "object" }, address: { type: "object", required: ["line1", "city", "state", "postalCode", "country"] }, paymentMethod: { type: "string", enum: ["RAZORPAY", "COD"] } }, description: "The purchase basket and totals are resolved from the authenticated session, never from client item prices." },
      OrderInput: { type: "object", required: ["items"], properties: { customerId: { type: "string", format: "uuid" }, items: { type: "array", items: { type: "object" } } } },
      PaymentInput: { type: "object", required: ["orderId", "method", "amount"], properties: { orderId: { type: "string", format: "uuid" }, method: { type: "string", enum: ["RAZORPAY", "COD"] }, amount: { type: "string", example: "500.00" } } },
      ArtworkInput: { type: "object", required: ["filename", "fileSize", "productId"], properties: { filename: { type: "string", example: "business-card.cdr" }, contentType: { type: "string", enum: ["application/octet-stream", "application/cdr", "application/vnd.corel-draw", "application/x-cdr"] }, fileSize: { type: "integer", minimum: 1 }, productId: { type: "string", format: "uuid" }, pricingRuleId: { type: ["string", "null"], format: "uuid" } }, description: "Customer artwork upload accepts CorelDRAW (.cdr) files only." },
      ArtworkRequirement: {
        type: "object",
        required: ["acceptedFormats"],
        properties: {
          pricingRuleId: { type: ["string", "null"], format: "uuid", description: "Optional deepest pricing/configuration scope. Null applies at product level." },
          artworkRequired: { type: "boolean", default: false },
          acceptedFormats: { type: "array", minItems: 1, maxItems: 2, uniqueItems: true, items: { type: "string", enum: ["CDR", "PDF"] } },
          minFileSize: { type: ["integer", "null"], minimum: 1 },
          maxFileSize: { type: ["integer", "null"], minimum: 1, description: "Maximum size in MB." },
          maxFiles: { type: "integer", minimum: 1, maximum: 10, default: 1 },
          designWidth: { type: ["string", "null"] }, designHeight: { type: ["string", "null"] }, designUnit: { type: "string", default: "mm" },
          safeAreaWidth: { type: ["string", "null"] }, safeAreaHeight: { type: ["string", "null"] },
          finalWidth: { type: ["string", "null"] }, finalHeight: { type: ["string", "null"] },
          orientation: { type: ["string", "null"], enum: ["PORTRAIT", "LANDSCAPE", "SQUARE", "ANY", null] },
          pageInstructions: { type: "array", maxItems: 20, items: { type: "object", required: ["pageNumber", "label"], properties: { pageNumber: { type: "integer", minimum: 1, maximum: 20 }, label: { type: "string" }, colorMode: { type: ["string", "null"] }, notes: { type: ["string", "null"] }, required: { type: "boolean", default: true } } } },
          multiplePageInstructions: { type: ["string", "null"] },
          additionalInstructions: { type: ["string", "null"] },
          notes: { type: ["string", "null"] },
          isActive: { type: "boolean", default: true },
        },
      },
      ProductCatalogMutation: { type: "object", required: ["resource", "data"], properties: { resource: { type: "string", enum: ["SECTION", "SECTION_ITEM", "ADDON", "DELIVERY_RULE", "PRICING_RULE", "ARTWORK_REQUIREMENT"] }, id: { type: "string", format: "uuid", description: "Required for PATCH and DELETE." }, data: { oneOf: [{ $ref: "#/components/schemas/ArtworkRequirement" }, { type: "object" }] } } },
      AdminInput: { type: "object", required: ["name", "email", "password"], properties: { name: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", format: "password" }, phoneNumber: { type: "string" } } },
      AdminMutation: { type: "object", description: "Use the endpoint-specific editable fields. Status enums include inquiry NEW/CONTACTED/CONVERTED, order PENDING through DELIVERED/CANCELLED, artwork PENDING_REVIEW/APPROVED/CHANGES_REQUIRED/REJECTED, and payment PENDING/PAID/FAILED/REFUNDED/COD_PENDING/COD_COLLECTED." },
    },
  },
} as const;
