"use client";

import Link from "next/link";
import { ClipboardList, CreditCard, FileCheck2, Package, RefreshCw, UserPlus, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";

type DashboardData = { ordersToday: number; pendingOrders: number; pendingQuotes: number; newInquiries: number; pendingPayments: number; pendingArtwork: number; pendingWalletRequests: number; recentOrders: { orderNumber: string; status: string; total: string }[]; recentQuotes: { quoteNumber: string; contactName: string; status: string; total: string }[] };
const metrics = [["Orders today", "ordersToday", Package, "/admin/orders"], ["Pending orders", "pendingOrders", FileCheck2, "/admin/orders"], ["Pending quotes", "pendingQuotes", ClipboardList, "/admin/quotes"], ["New inquiries", "newInquiries", UserPlus, "/admin/inquiries"], ["Pending payments", "pendingPayments", CreditCard, "/admin/payments"], ["Pending artwork", "pendingArtwork", FileCheck2, "/admin/artworks"], ["Wallet requests", "pendingWalletRequests", WalletCards, "/admin/wallet"]] as const;

export function AdminDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/admin/dashboard", { cache: "no-store" }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Could not load the dashboard"); setData(payload.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load the dashboard"); } finally { setLoading(false); } }
  useEffect(() => { async function loadDashboard() { try { const response = await fetch("/api/admin/dashboard", { cache: "no-store" }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Could not load the dashboard"); setData(payload.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load the dashboard"); } finally { setLoading(false); } } void loadDashboard(); }, []);
  return <div><div className="flex flex-col justify-between gap-4 border-b border-[#ddd9d0] pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#f15a3a]">Operations dashboard</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Today&apos;s work.</h1><p className="mt-2 text-sm text-[#646b64]">Live counts from the Mahavir Card database.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center justify-center gap-2 border border-[#cfcfc6] bg-white px-4 py-2.5 text-sm font-bold hover:border-[#18231e] disabled:opacity-60"><RefreshCw size={16} className={loading ? "animate-spin" : ""} /> Refresh</button></div>{error ? <div className="mt-6 border border-[#e9c4bd] bg-[#fff4f1] p-4 text-sm text-[#8b2f24]">{error}</div> : null}<div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(([label, key, Icon, href]) => <Link href={href} key={key} className="border border-[#ddd9d0] bg-white p-5 hover:border-[#18231e]"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#777d76]">{label}</p><Icon size={18} className="text-[#f15a3a]" /></div><p className="mt-5 text-3xl font-bold">{loading ? "..." : data?.[key] ?? 0}</p></Link>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Records title="Recent orders" href="/admin/orders" items={data?.recentOrders} render={(item) => <><span>{item.orderNumber}<small className="mt-1 block text-[#777d76]">{item.status}</small></span><strong>Rs {Number(item.total).toLocaleString("en-IN")}</strong></>} /><Records title="Recent quotes" href="/admin/quotes" items={data?.recentQuotes} render={(item) => <><span>{item.quoteNumber}<small className="mt-1 block text-[#777d76]">{item.contactName} / {item.status}</small></span><strong>Rs {Number(item.total).toLocaleString("en-IN")}</strong></>} /></div></div>;
}

function Records<T>({ title, href, items, render }: { title: string; href: string; items?: T[]; render: (item: T) => React.ReactNode }) {
  return <section className="border border-[#ddd9d0] bg-white"><div className="flex items-center justify-between border-b border-[#eeeae2] px-5 py-4"><h2 className="font-bold">{title}</h2><Link href={href} className="text-xs font-bold text-[#f15a3a]">View all</Link></div><div className="divide-y divide-[#eeeae2]">{items?.length ? items.map((item, index) => <div key={index} className="flex items-center justify-between gap-4 px-5 py-3 text-sm">{render(item)}</div>) : <p className="px-5 py-8 text-sm text-[#646b64]">No records yet.</p>}</div></section>;
}
