"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { useEffect, useState } from "react";

type Item = { productId: string; quantity: number; configuration: Record<string, string>; product: { name: string } };

export function CheckoutFlow() {
  const [items, setItems] = useState<Item[]>([]); const [method, setMethod] = useState<"RAZORPAY" | "COD">("COD"); const [form, setForm] = useState({ contactName: "", companyName: "", phone: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [result, setResult] = useState<{ order: { orderNumber: string }; payment: { method: string; status: string } } | null>(null);
  useEffect(() => { async function load() { try { const response = await fetch("/api/cart?kind=PURCHASE", { cache: "no-store" }); const payload = await response.json(); if (response.status === 401) throw new Error("Please sign in before checkout."); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Could not load your basket"); setItems(payload.data.items); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load your basket"); } finally { setLoading(false); } } void load(); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer: form, paymentMethod: method, items: items.map(({ productId, quantity, configuration }) => ({ productId, quantity, configuration })) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "We could not create this order."); await fetch("/api/cart?kind=PURCHASE", { method: "DELETE" }); setResult(payload.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "We could not create this order."); } finally { setLoading(false); } }
  if (result) return <div className="mx-auto max-w-xl py-20 text-center"><CheckCircle2 className="mx-auto text-[#8b2f24]" size={44} /><p className="mt-6 text-sm font-bold">Order {result.order.orderNumber} created.</p><p className="mt-3 text-sm text-[#646b64]">{result.payment.method === "COD" ? "Cash on delivery is pending." : "Razorpay payment remains pending until it is verified by the provider."}</p><Link href="/account" className="mt-7 inline-flex items-center gap-2 bg-[#17221c] px-5 py-3 text-sm font-bold text-white">View account <ArrowRight size={16} /></Link></div>;
  return <form onSubmit={submit} className="mx-auto max-w-2xl space-y-5 py-8"><div className="border-b border-[#dedcd5] pb-5"><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#8b2f24]">Checkout</p><h1 className="mt-2 text-3xl font-bold">Confirm your order.</h1></div><section className="border border-[#d8d6cf] bg-white p-5"><h2 className="font-bold">Items</h2>{loading ? <p className="mt-3 text-sm text-[#687069]">Loading basket...</p> : items.length ? <div className="mt-3 space-y-2">{items.map((item, index) => <p key={index} className="border-t border-[#eeeae2] pt-2 text-sm">{item.product.name} / Qty {item.quantity}</p>)}</div> : <p className="mt-3 text-sm text-[#687069]">No basket items. <Link href="/catalog" className="font-bold text-[#8b2f24]">Browse products</Link></p>}</section><section className="border border-[#d8d6cf] bg-white p-5"><h2 className="font-bold">Customer details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["contactName", "Contact name"], ["companyName", "Company name"], ["phone", "Mobile number"]].map(([key, label]) => <label key={key}><span className="mb-2 block text-xs font-bold">{label}</span><input required value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="w-full border border-[#d8d6cf] bg-[#fcfbf8] px-3 py-3 text-sm outline-none" /></label>)}</div><div className="mt-4 flex gap-2"><button type="button" onClick={() => setMethod("COD")} className={`border px-3 py-2 text-sm font-bold ${method === "COD" ? "border-[#17221c] bg-[#17221c] text-white" : "border-[#d8d6cf]"}`}>Cash on delivery</button><button type="button" onClick={() => setMethod("RAZORPAY")} className={`border px-3 py-2 text-sm font-bold ${method === "RAZORPAY" ? "border-[#17221c] bg-[#17221c] text-white" : "border-[#d8d6cf]"}`}>Razorpay</button></div></section>{error ? <p className="border border-[#e9c4bd] bg-[#fff4f1] p-3 text-sm text-[#8b2f24]">{error}</p> : null}<button disabled={!items.length || loading} className="flex w-full items-center justify-center gap-2 bg-[#8b2f24] px-5 py-4 text-sm font-bold text-white disabled:opacity-50">{method === "COD" ? "Place COD order" : "Create payment request"} <ArrowRight size={16} /></button></form>;
}
