import Link from "next/link";
import { ArrowRight, Clock3 } from "lucide-react";

import type { CatalogProduct } from "@/lib/catalog";
import { ProductImage } from "@/components/product-image";

export function ProductCard({ product }: { product: CatalogProduct & { priceLabel: string } }) {
  return <article className="group overflow-hidden rounded-lg border border-[#d8d6cf] bg-white transition hover:border-[#8b2f24] hover:shadow-[0_12px_28px_rgba(25,31,27,0.08)]"><Link href={`/catalog/${product.slug}`} className="relative block aspect-[1.45] overflow-hidden bg-[#ece7de]"><ProductImage src={product.imageUrl} alt={`${product.name} print sample`} slug={product.slug} /><div className="absolute inset-x-0 top-0 flex items-center justify-between p-3"><span className="bg-[#fcfbf8]/95 px-3 py-1.5 text-xs font-bold uppercase text-[#3b453e]">{product.category}</span>{product.orderable && <span className="bg-[#1f2c25] px-3 py-1.5 text-xs font-bold uppercase text-white">Buy online</span>}</div></Link><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold text-[#152019]">{product.name}</h3><p className="mt-1.5 text-[15px] leading-6 text-[#626a62]">{product.shortDescription}</p></div><Clock3 className="mt-1 shrink-0 text-[#6d746d]" size={18} /></div><div className="mt-5 flex items-end justify-between border-t border-[#ebe9e3] pt-4"><div><p className="text-xs font-bold uppercase text-[#747b74]">Pricing</p><p className="mt-1.5 text-lg font-bold text-[#18231e]">{product.priceLabel}</p><p className="mt-0.5 text-xs text-[#747b74]">GST charged additionally as applicable</p></div><span className="text-sm text-[#6d746d]">{product.turnaround}</span></div><div className="mt-5 grid grid-cols-2 gap-2.5"><Link href={`/catalog/${product.slug}`} className="inline-flex items-center justify-center gap-1.5 border border-[#cfcfc8] px-4 py-2.5 text-sm font-bold text-[#243027] hover:border-[#243027]">Configure <ArrowRight size={16} /></Link><Link href={`/catalog/${product.slug}`} className="inline-flex items-center justify-center gap-1.5 bg-[#8b2f24] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#17221c]">Order now <ArrowRight size={16} /></Link></div></div></article>;
}
