"use client";

import Link from "next/link";
import { FileUp, Search, SlidersHorizontal, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";

type Product = { id: string; name: string; slug: string; shortDescription: string | null; category: { name: string; slug: string } | null; startingPrice: number | null; referenceQuantity: number | null; orderable: boolean; quoteable: boolean; hasAddons: boolean; hasArtworkRequirement: boolean };
type Category = { id: string; name: string; slug: string };

export function ProductsBrowser() {
  const params = useSearchParams();
  const [items, setItems] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [query, setQuery] = useState(() => params.get("q") ?? ""); const [category, setCategory] = useState(() => params.get("category") ?? ""); const [orderable, setOrderable] = useState(() => params.get("orderable") === "true"); const [quoteable, setQuoteable] = useState(() => params.get("quoteable") === "true"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; fetch("/api/categories").then((response) => response.json()).then((payload) => { if (active && payload.success) setCategories(payload.data); }).catch(() => undefined); return () => { active = false; }; }, []);
  useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams(); if (query.trim()) params.set("q", query.trim()); if (category) params.set("category", category); if (orderable) params.set("orderable", "true"); if (quoteable) params.set("quoteable", "true"); fetch(`/api/products?${params}`, { signal: controller.signal }).then((response) => response.json()).then((payload) => { if (payload.success) { setItems(payload.data); setError(""); } else setError("Products could not be loaded."); }).catch((caught) => { if (caught.name !== "AbortError") setError("Products could not be loaded."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [category, orderable, query, quoteable]);
  const clear = () => { setQuery(""); setCategory(""); setOrderable(false); setQuoteable(false); };
  return <main className="min-h-screen bg-[#f7f9fc] text-[#162237]"><div className="mx-auto max-w-[1440px] px-4 py-7 xl:px-8"><header className="border-b border-[#d9e0eb] pb-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#2457b8]">All products</p><div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold sm:text-4xl">Choose a print job and configure it.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#607089]">Compare products, see starting prices, then go straight to the configuration screen.</p></div><p className="text-sm font-semibold text-[#52647e]">{items.length} products</p></div></header>
    <div className="mt-6 grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto]"><label className="flex items-center gap-3 border border-[#cfd8e8] bg-white px-3"><Search size={17} className="text-[#607089]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search business cards, labels, brochures..." className="min-w-0 flex-1 py-3 text-sm outline-none" />{query ? <button type="button" onClick={() => setQuery("")} aria-label="Clear search"><X size={16} /></button> : null}</label><button type="button" onClick={clear} className="border border-[#cfd8e8] bg-white px-4 py-3 text-sm font-bold text-[#2457b8]">Clear filters</button></div>
    <div className="mt-3 flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.11em] text-[#607089]"><SlidersHorizontal size={14} />Categories</span><div className="flex flex-wrap gap-2" role="group" aria-label="Product category filters"><button type="button" onClick={() => setCategory("")} className={`border px-3 py-2 text-sm font-semibold ${!category ? "border-[#2457b8] bg-[#2457b8] text-white" : "border-[#cfd8e8] bg-white text-[#52647e]"}`}>All categories</button>{categories.map((item) => <button type="button" key={item.id} onClick={() => setCategory(item.slug)} className={`border px-3 py-2 text-sm font-semibold ${category === item.slug ? "border-[#2457b8] bg-[#2457b8] text-white" : "border-[#cfd8e8] bg-white text-[#52647e]"}`}>{item.name}</button>)}</div><label className="flex items-center gap-2 border border-[#cfd8e8] bg-white px-3 py-2 text-sm"><input type="checkbox" checked={orderable} onChange={(event) => setOrderable(event.target.checked)} className="size-4 accent-[#2457b8]" />Buy online</label><label className="flex items-center gap-2 border border-[#cfd8e8] bg-white px-3 py-2 text-sm"><input type="checkbox" checked={quoteable} onChange={(event) => setQuoteable(event.target.checked)} className="size-4 accent-[#2457b8]" />Quote available</label></div>
    {error ? <p className="mt-6 border border-[#ecc9c5] bg-white p-4 text-sm font-semibold text-[#a53025]">{error}</p> : null}{loading ? <p className="mt-6 border border-[#d9e0eb] bg-white p-5 text-sm text-[#607089]">Loading products...</p> : null}
    {!loading && !error ? <section className="mt-6 overflow-x-auto border border-[#d9e0eb] bg-white"><div className="min-w-[780px]">
      <div className="grid grid-cols-[minmax(15rem,1.5fr)_minmax(12rem,1fr)_9rem_8rem_13rem] gap-4 border-b border-[#d9e0eb] bg-[#f2f6fc] px-5 py-3 text-xs font-bold uppercase tracking-[0.1em] text-[#52647e]"><span>Product</span><span>Specification</span><span>Starting price</span><span>Details</span><span>Actions</span></div>
      {items.map((item) => <article key={item.id} className="grid grid-cols-[minmax(15rem,1.5fr)_minmax(12rem,1fr)_9rem_8rem_13rem] gap-4 border-b border-[#e5eaf2] px-5 py-4 last:border-0">
        <div><p className="font-bold text-[#162237]">{item.name}</p><p className="mt-1 text-xs text-[#607089]">{item.category?.name ?? "Print product"}</p></div>
        <div><p className="text-sm text-[#52647e]">{item.shortDescription || "Configure print, quantity, and delivery."}</p><p className="mt-1 text-xs text-[#607089]">Reference quantity: {item.referenceQuantity?.toLocaleString("en-IN") ?? "on configuration"}</p></div>
        <div className="font-bold text-[#2457b8]">{item.startingPrice === null ? "On request" : `From Rs ${item.startingPrice.toLocaleString("en-IN")}`}</div>
        <div className="space-y-1 text-xs text-[#52647e]"><p>{item.hasAddons ? "Add-ons available" : "No add-ons"}</p>{item.hasArtworkRequirement ? <p className="inline-flex items-center gap-1"><FileUp size={13} />CDR required</p> : null}</div>
        <div className="flex flex-wrap gap-2"><Link href={`/catalog/${item.slug}`} className="bg-[#2457b8] px-3 py-2 text-xs font-bold text-white">Configure</Link>{item.orderable ? <Link href={`/catalog/${item.slug}?intent=buy`} className="border border-[#aebed8] px-3 py-2 text-xs font-bold text-[#2457b8]">Buy now</Link> : null}{item.quoteable ? <Link href={`/catalog/${item.slug}?intent=quote`} className="border border-[#cfd8e8] px-3 py-2 text-xs font-bold text-[#52647e]">Quote</Link> : null}</div>
      </article>)}
      {!items.length ? <div className="px-5 py-12 text-center text-sm text-[#607089]">No products match these filters.</div> : null}
    </div></section> : null}
  </div></main>;
}
