import Link from "next/link";
import { ArrowRight, Clock3, ReceiptText } from "lucide-react";

import type { CatalogProduct } from "@/lib/catalog";
import { ProductImage } from "@/components/product-image";

export function ProductCard({ product }: { product: CatalogProduct }) {
  return <article className="group overflow-hidden border border-[#d8d6cf] bg-white transition hover:border-[#8b2f24] hover:shadow-[0_12px_28px_rgba(25,31,27,0.08)]"><Link href={`/catalog/${product.slug}`} className="relative block aspect-[1.45] overflow-hidden bg-[#ece7de]"><ProductImage src={product.imageUrl} alt={`${product.name} print sample`} slug={product.slug} /><div className="absolute inset-x-0 top-0 flex items-center justify-between p-3"><span className="bg-[#fcfbf8]/95 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-[#3b453e]">{product.category}</span>{product.orderable && <span className="bg-[#1f2c25] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-white">Buy online</span>}</div></Link><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-[#152019]">{product.name}</h3><p className="mt-1 text-sm leading-5 text-[#626a62]">{product.shortDescription}</p></div><Clock3 className="mt-1 shrink-0 text-[#6d746d]" size={16} /></div><div className="mt-4 flex items-end justify-between border-t border-[#ebe9e3] pt-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#747b74]">{product.orderable ? "From" : "Pricing"}</p><p className="mt-1 text-sm font-bold text-[#18231e]">{product.orderable ? `Rs ${product.startingPrice.toLocaleString("en-IN")} / ${product.unit}` : "Request a tailored quote"}</p></div><span className="text-xs text-[#6d746d]">{product.turnaround}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Link href={`/catalog/${product.slug}`} className="inline-flex items-center justify-center gap-1.5 border border-[#cfcfc8] px-3 py-2.5 text-xs font-bold text-[#243027] hover:border-[#243027]">Configure <ArrowRight size={14} /></Link>{product.orderable ? <Link href={`/catalog/${product.slug}`} className="inline-flex items-center justify-center gap-1.5 bg-[#8b2f24] px-3 py-2.5 text-xs font-bold text-white hover:bg-[#17221c]">Buy now <ArrowRight size={14} /></Link> : <Link href={`/catalog/${product.slug}`} className="inline-flex items-center justify-center gap-1.5 bg-[#17221c] px-3 py-2.5 text-xs font-bold text-white hover:bg-[#8b2f24]">Quote <ReceiptText size={14} /></Link>}</div></div></article>;
}
