"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Check, ChevronLeft, CircleAlert, ExternalLink, ImagePlus, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { adminRequest, asItems, formattedAmount } from "@/lib/admin-client";
import { ArtworkRequirementsPanel, ConfigurationAddonsPanel } from "@/components/product-configuration-admin";

type Row = Record<string, unknown>;
type Tab = "overview" | "images" | "description" | "pricing" | "addons" | "delivery" | "artwork";
const tabs: { id: Tab; label: string }[] = [{ id: "overview", label: "Overview" }, { id: "images", label: "Images" }, { id: "description", label: "Description" }, { id: "pricing", label: "Pricing" }, { id: "addons", label: "Add-ons" }, { id: "delivery", label: "Delivery" }, { id: "artwork", label: "Artwork" }];

function text(value: unknown) { return value === null || value === undefined ? "" : String(value); }
function bool(value: unknown, fallback = false) { return typeof value === "boolean" ? value : fallback; }
function number(value: unknown) { return Number(value || 0); }
function optionalNumber(value: unknown) { return text(value).trim() ? Number(value) : null; }
function json(value: unknown) { return JSON.stringify(value ?? {}, null, 2); }
function parseJson(value: string, label: string) { try { return JSON.parse(value || "{}"); } catch { throw new Error(`${label} must be valid JSON.`); } }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "The request could not be completed."; }
function productId(value: Row | null) { return text(value?.id); }

export function ProductList() {
  const [items, setItems] = useState<Row[]>([]);
  const [categories, setCategories] = useState<Row[]>([]);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function load() {
    setLoading(true); setError("");
    try {
      const [products, categoryList] = await Promise.all([
        adminRequest<Row[] | { items?: Row[] }>("/api/admin/products?limit=100"),
        adminRequest<Row[]>("/api/admin/categories"),
      ]);
      setItems(asItems(products)); setCategories(categoryList);
    } catch (caught) { setError(errorMessage(caught)); } finally { setLoading(false); }
  }
  useEffect(() => {
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  const visible = useMemo(() => items.filter((item) => {
    const matchesQuery = `${text(item.name)} ${text(item.slug)} ${text(item.productCode)}`.toLowerCase().includes(query.trim().toLowerCase());
    return matchesQuery && (!category || text(item.categoryId) === category) && (!status || text(item.status) === status);
  }), [category, items, query, status]);
  const categoryName = (id: unknown) => categories.find((item) => text(item.id) === text(id))?.name ?? "Uncategorised";
  return <div>
    <header className="flex flex-col justify-between gap-4 border-b border-[#d7dce5] pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#2457b8]">Catalogue CMS</p><h1 className="mt-2 text-2xl font-bold text-[#162237] sm:text-3xl">Products</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#607089]">Create products, control availability, and configure the content and pricing used by customers.</p></div><div className="flex gap-2"><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 border border-[#c9d2df] bg-white px-3 py-2.5 text-sm font-bold text-[#24324a]"><RefreshCw size={16} className={loading ? "animate-spin" : ""} />Refresh</button><Link href="/admin/products/new" className="inline-flex items-center gap-2 bg-[#2457b8] px-3 py-2.5 text-sm font-bold text-white hover:bg-[#17479f]"><Plus size={16} />New product</Link></div></header>
    {error ? <Message tone="error">{error}</Message> : null}
    <div className="mt-6 grid gap-3 md:grid-cols-[minmax(0,1fr)_12rem_10rem]"><label className="flex items-center gap-3 border border-[#cfd7e3] bg-white px-3"><Search size={17} className="text-[#607089]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" className="min-w-0 flex-1 py-3 text-sm outline-none" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} className="border border-[#cfd7e3] bg-white px-3 py-3 text-sm"><option value="">All categories</option>{categories.map((item) => <option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="border border-[#cfd7e3] bg-white px-3 py-3 text-sm"><option value="">All statuses</option>{["ACTIVE", "DRAFT", "DISABLED", "ARCHIVED"].map((value) => <option key={value}>{value}</option>)}</select></div>
    {loading ? <div className="mt-6 border border-[#d7dce5] bg-white p-6 text-sm text-[#607089]">Loading products...</div> : null}
    {!loading && !visible.length ? <div className="mt-6 border border-dashed border-[#c9d2df] bg-white p-8 text-center"><p className="font-bold">No products found.</p><p className="mt-2 text-sm text-[#607089]">Create a product to make it available for catalogue configuration.</p></div> : null}
    {!loading && visible.length ? <><div className="mt-6 space-y-3 md:hidden">{visible.map((item) => <ProductCard key={productId(item)} item={item} categoryName={text(categoryName(item.categoryId))} />)}</div><div className="mt-6 hidden overflow-x-auto border border-[#d7dce5] bg-white md:block"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#d7dce5] bg-[#f7f9fc]"><tr>{["Product", "Category", "Availability", "Customer path", "Actions"].map((label) => <th key={label} className="px-4 py-3 text-xs font-bold uppercase tracking-[0.1em] text-[#52647e]">{label}</th>)}</tr></thead><tbody>{visible.map((item) => <tr key={productId(item)} className="border-b border-[#e8ecf2] last:border-0"><td className="px-4 py-3"><p className="font-bold text-[#162237]">{text(item.name)}</p><p className="mt-1 text-xs text-[#607089]">{text(item.slug)}</p></td><td className="px-4 py-3 text-[#52647e]">{text(categoryName(item.categoryId))}</td><td className="px-4 py-3"><Status value={text(item.status)} active={bool(item.isActive)} /></td><td className="px-4 py-3 text-[#52647e]">{bool(item.orderable) ? "Direct payment" : ""}{bool(item.orderable) && bool(item.quoteable) ? " + " : ""}{bool(item.quoteable) ? "Quote" : ""}</td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/admin/products/${productId(item)}`} className="border border-[#c9d2df] px-2.5 py-1.5 text-xs font-bold text-[#2457b8]">Manage</Link><Link href={`/catalog/${text(item.slug)}`} target="_blank" className="border border-[#c9d2df] p-1.5 text-[#52647e]" aria-label="Open customer page"><ExternalLink size={14} /></Link></div></td></tr>)}</tbody></table></div></> : null}</div>;
}

function ProductCard({ item, categoryName }: { item: Row; categoryName: string }) { return <article className="border border-[#d7dce5] bg-white p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-[#162237]">{text(item.name)}</p><p className="mt-1 text-xs text-[#607089]">{text(item.slug)} · {categoryName}</p></div><Status value={text(item.status)} active={bool(item.isActive)} /></div><div className="mt-4 flex gap-2"><Link href={`/admin/products/${productId(item)}`} className="border border-[#c9d2df] px-3 py-2 text-xs font-bold text-[#2457b8]">Manage product</Link><Link href={`/catalog/${text(item.slug)}`} target="_blank" className="border border-[#c9d2df] p-2 text-[#52647e]" aria-label="Open customer page"><ExternalLink size={15} /></Link></div></article>; }

export function ProductEditor({ productId: id }: { productId?: string }) {
  const router = useRouter(); const searchParams = useSearchParams();
  const requestedTab = searchParams.get("tab") as Tab | null;
  const [tab, setTab] = useState<Tab>("overview");
  const [product, setProduct] = useState<Row | null>(null); const [catalog, setCatalog] = useState<Row | null>(null); const [categories, setCategories] = useState<Row[]>([]); const [addons, setAddons] = useState<Row[]>([]);
  const [loading, setLoading] = useState(Boolean(id)); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { const [categoryResult, addonResult] = await Promise.all([adminRequest<Row[]>("/api/admin/categories"), adminRequest<Row[]>("/api/admin/addons")]); setCategories(categoryResult); setAddons(addonResult); if (id) { const [productResult, catalogResult] = await Promise.all([adminRequest<Row>(`/api/admin/products/${id}`), adminRequest<Row>(`/api/admin/products/${id}/catalog`)]); setProduct(productResult); setCatalog(catalogResult); } } catch (caught) { setError(errorMessage(caught)); } finally { setLoading(false); } }
  useEffect(() => {
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, [id]); // eslint-disable-line react-hooks/exhaustive-deps
  async function saveOverview(data: Row) { setError(""); try { const result = await adminRequest<Row>(id ? `/api/admin/products/${id}` : "/api/admin/products", { method: id ? "PATCH" : "POST", body: JSON.stringify(data) }); if (!id) { router.replace(`/admin/products/${text(result.id)}`); return; } setProduct(result); setNotice("Product saved."); } catch (caught) { setError(errorMessage(caught)); throw caught; } }
  async function mutateCatalog(method: "POST" | "PATCH" | "DELETE", resource: string, data: Row = {}, resourceId?: string) { if (!id) return; setError(""); try { await adminRequest(`/api/admin/products/${id}/catalog`, { method, body: JSON.stringify(method === "DELETE" ? { resource, id: resourceId } : { resource, ...(resourceId ? { id: resourceId } : {}), data }) }); setNotice("Catalogue configuration saved."); await load(); } catch (caught) { setError(errorMessage(caught)); throw caught; } }
  if (loading) return <div className="border border-[#d7dce5] bg-white p-6 text-sm text-[#607089]">Loading product configuration...</div>;
  if (error && !product && id) return <div><Message tone="error">{error}</Message><Link href="/admin/products" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#2457b8]"><ChevronLeft size={16} />Back to products</Link></div>;
  const activeTab = requestedTab && tabs.some((item) => item.id === requestedTab) ? requestedTab : tab;
  return <div><header className="flex flex-col justify-between gap-4 border-b border-[#d7dce5] pb-6 sm:flex-row sm:items-end"><div><Link href="/admin/products" className="inline-flex items-center gap-1 text-sm font-semibold text-[#2457b8]"><ChevronLeft size={16} />Products</Link><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-[#2457b8]">Catalogue CMS</p><h1 className="mt-2 text-2xl font-bold text-[#162237] sm:text-3xl">{id ? text(product?.name) : "New product"}</h1><p className="mt-2 text-sm text-[#607089]">{id ? "Everything customer-facing for this product is managed here." : "Create the base product before adding pricing, delivery, and product content."}</p></div>{id && product ? <Link href={`/catalog/${text(product.slug)}`} target="_blank" className="inline-flex items-center gap-2 border border-[#c9d2df] bg-white px-3 py-2.5 text-sm font-bold text-[#24324a]"><ExternalLink size={16} />Customer page</Link> : null}</header>
    {error ? <Message tone="error" onDismiss={() => setError("")}>{error}</Message> : null}{notice ? <Message tone="success" onDismiss={() => setNotice("")}>{notice}</Message> : null}
    {id ? <nav className="mt-6 flex gap-1 overflow-x-auto border-b border-[#d7dce5]" aria-label="Product settings">{tabs.map((item) => <button type="button" key={item.id} onClick={() => setTab(item.id)} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-bold ${activeTab === item.id ? "border-[#2457b8] text-[#2457b8]" : "border-transparent text-[#607089] hover:text-[#162237]"}`}>{item.label}</button>)}</nav> : null}
    <section className="mt-6 border border-[#d7dce5] bg-white p-4 sm:p-6">{activeTab === "overview" || !id ? <OverviewForm product={product} categories={categories} onSave={saveOverview} /> : null}{activeTab === "images" && id ? <ImagesPanel productId={id} rows={array(catalog?.images)} onChanged={load} /> : null}{activeTab === "description" ? <DescriptionPanel rows={array(catalog?.sections)} mutate={mutateCatalog} /> : null}{activeTab === "pricing" ? <PricingPanel rows={array(catalog?.pricingRules)} mutate={mutateCatalog} /> : null}{activeTab === "addons" ? <ConfigurationAddonsPanel rows={array(catalog?.addons)} addons={addons} pricingRules={array(catalog?.pricingRules)} mutate={mutateCatalog} /> : null}{activeTab === "delivery" ? <div className="space-y-8"><DeliveryPanel rows={array(catalog?.deliveryRules)} mutate={mutateCatalog} /><LocationSurchargesPanel rows={array(catalog?.locationSurcharges)} pricingRules={array(catalog?.pricingRules)} mutate={mutateCatalog} /></div> : null}{activeTab === "artwork" ? <ArtworkRequirementsPanel rows={array(catalog?.artworkRequirements)} pricingRules={array(catalog?.pricingRules)} mutate={mutateCatalog} /> : null}</section></div>;
}

function OverviewForm({ product, categories, onSave }: { product: Row | null; categories: Row[]; onSave: (data: Row) => Promise<void> }) {
  const [form, setForm] = useState(() => productForm(product)); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const update = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const toggle = (key: string) => (event: React.ChangeEvent<HTMLInputElement>) => setForm((current) => ({ ...current, [key]: event.target.checked }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await onSave({ ...form, categoryId: form.categoryId || null, description: empty(form.description), shortDescription: empty(form.shortDescription), productCode: empty(form.productCode), productReference: empty(form.productReference), productClass: empty(form.productClass), productionTime: empty(form.productionTime), artworkInstructions: empty(form.artworkInstructions), referenceQuantity: form.referenceQuantity ? number(form.referenceQuantity) : null, referenceWeight: empty(form.referenceWeight), referenceWeightUnit: empty(form.referenceWeightUnit), sortOrder: number(form.sortOrder), configuration: parseJson(form.configuration, "Configuration") }); } catch (caught) { setError(errorMessage(caught)); } finally { setSaving(false); } }
  return <form onSubmit={submit}><PanelTitle title="Product details" description="This controls the main catalogue card and whether customers can buy or request a quote." /><div className="mt-6 grid gap-4 sm:grid-cols-2">{input("Product name", "name", form, update, true)}{input("Slug", "slug", form, update, true, "text", "business-cards")}<label className="block text-sm font-semibold text-[#263753]"><span>Category</span><select value={form.categoryId} onChange={update("categoryId")} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 text-sm font-normal"><option value="">Uncategorised</option>{categories.map((item) => <option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</select></label><label className="block text-sm font-semibold text-[#263753]"><span>Status</span><select value={form.status} onChange={update("status")} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 text-sm font-normal">{["DRAFT", "ACTIVE", "DISABLED", "ARCHIVED"].map((value) => <option key={value}>{value}</option>)}</select></label>{input("Product code", "productCode", form, update)}{input("Reference", "productReference", form, update)}{input("Product class", "productClass", form, update)}{input("Production time", "productionTime", form, update, false, "text", "3-5 working days")}<div className="sm:col-span-2">{textarea("Short description", "shortDescription", form, update, 3)}</div><div className="sm:col-span-2">{textarea("Full description", "description", form, update, 5)}</div>{input("Display order", "sortOrder", form, update, true, "number")}{input("Reference quantity", "referenceQuantity", form, update, false, "number")}{input("Reference weight", "referenceWeight", form, update, false, "text", "0.250")} {input("Weight unit", "referenceWeightUnit", form, update, false, "text", "kg")}<div className="sm:col-span-2">{textarea("Product configuration (JSON)", "configuration", form, update, 4)}</div></div><div className="mt-5 flex flex-wrap gap-x-6 gap-y-3 border-t border-[#e4e8ef] pt-5">{checkbox("isActive", "Visible to staff", form, toggle)}{checkbox("orderable", "Allow direct payment", form, toggle)}{checkbox("quoteable", "Allow quote request", form, toggle)}{checkbox("pricesTaxInclusive", "Prices include tax", form, toggle)}{checkbox("artworkRequired", "Artwork required", form, toggle)}</div>{form.artworkRequired ? <div className="mt-4">{textarea("Artwork instructions", "artworkInstructions", form, update, 4)}</div> : null}<SaveButton saving={saving} />{error ? <p className="mt-3 text-sm font-semibold text-[#b13a2f]">{error}</p> : null}</form>;
}

function ImagesPanel({ productId, rows, onChanged }: { productId: string; rows: Row[]; onChanged: () => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [altText, setAltText] = useState(""); const [isPrimary, setIsPrimary] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function request(url: string, options: RequestInit) { const response = await fetch(url, options); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error?.message || "Image request failed."); return payload; }
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; setSaving(true); setError(""); try { const body = new FormData(); body.append("file", file); body.append("altText", altText); body.append("sortOrder", String(rows.length)); body.append("isPrimary", String(isPrimary)); await request(`/api/admin/products/${productId}/images`, { method: "POST", body }); setFile(null); setAltText(""); setIsPrimary(false); await onChanged(); } catch (caught) { setError(errorMessage(caught)); } finally { setSaving(false); } }
  async function update(row: Row, data: Row) { setError(""); try { await request(`/api/admin/products/${productId}/images/${text(row.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); await onChanged(); } catch (caught) { setError(errorMessage(caught)); } }
  async function replace(row: Row, replacement: File) { setError(""); try { const body = new FormData(); body.append("file", replacement); body.append("altText", text(row.altText)); body.append("sortOrder", text(row.sortOrder)); body.append("isPrimary", String(bool(row.isPrimary))); await request(`/api/admin/products/${productId}/images/${text(row.id)}`, { method: "PATCH", body }); await onChanged(); } catch (caught) { setError(errorMessage(caught)); } }
  async function remove(row: Row) { setError(""); try { await request(`/api/admin/products/${productId}/images/${text(row.id)}`, { method: "DELETE" }); await onChanged(); } catch (caught) { setError(errorMessage(caught)); } }
  return <div><PanelTitle title="Product images" description="Upload customer-visible product images to Cloudflare R2. The bucket remains private and images are delivered through temporary read URLs." />
    <form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={upload}><label className="text-sm font-semibold"><span>Image file</span><input required accept="image/jpeg,image/png,image/webp,image/avif" type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="mt-1.5 block w-full border border-[#c9d2df] bg-white px-3 py-2 text-sm" /></label>{input("Alt text", "altText", { altText }, () => (event) => setAltText(event.target.value))}<label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={isPrimary} onChange={(event) => setIsPrimary(event.target.checked)} className="size-4 accent-[#2457b8]" />Set as primary image</label><button disabled={saving || !file} className="inline-flex w-fit items-center gap-2 bg-[#2457b8] px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><ImagePlus size={15} />{saving ? "Uploading..." : "Upload image"}</button></form>
    {error ? <Message tone="error">{error}</Message> : null}
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map((row) => <article key={text(row.id)} className="border border-[#d7dce5] p-3"><a href={text(row.imageUrl)} target="_blank" className="block h-32 overflow-hidden bg-[#f5f7fa] bg-cover bg-center" style={{ backgroundImage: `url("${text(row.imageUrl)}")` }} aria-label={text(row.altText) || "Product image"} /><p className="mt-3 truncate text-sm font-bold">{text(row.altText) || text(row.originalFilename) || "Product image"}</p><div className="mt-2 flex items-center gap-2"><span className="text-xs text-[#607089]">Order</span><input type="number" min="0" defaultValue={text(row.sortOrder)} onBlur={(event) => { if (event.target.value !== text(row.sortOrder)) void update(row, { sortOrder: number(event.target.value) }); }} className="w-16 border border-[#c9d2df] px-2 py-1 text-xs" />{bool(row.isPrimary) ? <span className="text-xs font-bold text-[#2457b8]">Primary</span> : null}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => void update(row, { isPrimary: true })} disabled={bool(row.isPrimary)} className="border border-[#c9d2df] px-2 py-1.5 text-xs font-bold disabled:opacity-50">Set primary</button><label className="cursor-pointer border border-[#c9d2df] px-2 py-1.5 text-xs font-bold">Replace<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={(event) => { const replacement = event.target.files?.[0]; event.currentTarget.value = ""; if (replacement) void replace(row, replacement); }} /></label><DeleteButton onClick={() => remove(row)} /></div></article>)}</div>
  </div>;
}

function DescriptionPanel({ rows, mutate }: { rows: Row[]; mutate: CatalogMutation }) { const [title, setTitle] = useState(""); return <div><PanelTitle title="Structured description" description="Add customer-facing sections and rows in their display order." /><form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={async (event) => { event.preventDefault(); await mutate("POST", "SECTION", { title, sortOrder: rows.length }); setTitle(""); }}><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Section title, e.g. Print specifications" className="min-w-0 flex-1 border border-[#c9d2df] px-3 py-2.5 text-sm" /><button className="inline-flex items-center justify-center gap-2 bg-[#2457b8] px-3 py-2.5 text-sm font-bold text-white"><Plus size={16} />Add section</button></form><div className="mt-6 space-y-4">{rows.map((section) => <ContentSection key={text(section.id)} section={section} mutate={mutate} />)}</div></div>; }

function ContentSection({ section, mutate }: { section: Row; mutate: CatalogMutation }) { const [title, setTitle] = useState(text(section.title)); const [label, setLabel] = useState(""); const [content, setContent] = useState(""); const items = array(section.items); return <section className="border border-[#d7dce5] p-4"><div className="flex flex-col gap-3 sm:flex-row"><input value={title} onChange={(event) => setTitle(event.target.value)} className="min-w-0 flex-1 border border-[#c9d2df] px-3 py-2 text-sm font-bold" /><button type="button" onClick={() => void mutate("PATCH", "SECTION", { title }, text(section.id))} className="border border-[#c9d2df] px-3 py-2 text-xs font-bold">Save title</button><DeleteButton onClick={() => mutate("DELETE", "SECTION", {}, text(section.id))} /></div><div className="mt-4 divide-y divide-[#e8ecf2]">{items.map((item) => <ContentItem key={text(item.id)} item={item} mutate={mutate} />)}</div><form className="mt-4 grid gap-2 sm:grid-cols-[12rem_minmax(0,1fr)_auto]" onSubmit={async (event) => { event.preventDefault(); await mutate("POST", "SECTION_ITEM", { sectionId: text(section.id), label: label || null, content, sortOrder: items.length }); setLabel(""); setContent(""); }}><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Label" className="border border-[#c9d2df] px-3 py-2 text-sm" /><input required value={content} onChange={(event) => setContent(event.target.value)} placeholder="Content" className="border border-[#c9d2df] px-3 py-2 text-sm" /><button className="bg-[#edf3ff] px-3 py-2 text-sm font-bold text-[#2457b8]">Add row</button></form></section>; }
function ContentItem({ item, mutate }: { item: Row; mutate: CatalogMutation }) { const [label, setLabel] = useState(text(item.label)); const [content, setContent] = useState(text(item.content)); return <div className="grid gap-2 py-3 sm:grid-cols-[12rem_minmax(0,1fr)_auto]"><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Label" className="border border-[#c9d2df] px-2 py-1.5 text-sm" /><input value={content} onChange={(event) => setContent(event.target.value)} className="border border-[#c9d2df] px-2 py-1.5 text-sm" /><div className="flex gap-2"><button type="button" onClick={() => void mutate("PATCH", "SECTION_ITEM", { label: label || null, content }, text(item.id))} className="border border-[#c9d2df] px-2 py-1.5 text-xs font-bold">Save</button><DeleteButton onClick={() => mutate("DELETE", "SECTION_ITEM", {}, text(item.id))} /></div></div>; }

function PricingPanel({ rows, mutate }: { rows: Row[]; mutate: CatalogMutation }) { return <div><PanelTitle title="Pricing rules" description="Set base amounts and square-inch rates with GST handled separately at checkout." /><PricingRuleForm mutate={mutate} /><div className="mt-6 space-y-3">{rows.map((row) => <PricingRuleForm key={text(row.id)} row={row} mutate={mutate} />)}</div></div>; }
function PricingRuleForm({ row, mutate }: { row?: Row; mutate: CatalogMutation }) {
  const conditions = object(row?.conditions) ?? {};
  const formula = object(row?.priceFormula) ?? {};
  const [form, setForm] = useState({ name: text(row?.name), ruleType: text(row?.ruleType) || "FIXED_PER_REFERENCE_QUANTITY", referenceQuantity: text(conditions.quantity) || "1", baseAmount: text(formula.amount), rateUnit: text(formula.rateUnit) || (formula.ratePaisePerSqInch ? "PAISE" : "RUPEES"), rateValue: text(formula.ratePaisePerSqInch ?? formula.ratePerSqInch), minimumArea: text(formula.minimumArea), minimumCharge: text(formula.minimumCharge), bladeCharge: text(formula.bladeCharge), taxRate: text(row?.taxRate) || "18", productionTime: text(row?.productionTime), sortOrder: text(row?.sortOrder) || "0", taxInclusive: bool(row?.taxInclusive), isActive: bool(row?.isActive, true) });
  const update = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const save = async (event: FormEvent) => { event.preventDefault(); const priceFormula = form.ruleType === "PER_SQ_INCH" ? { ...formula, amount: undefined, rateUnit: form.rateUnit, ratePaisePerSqInch: form.rateUnit === "PAISE" ? number(form.rateValue) : null, ratePerSqInch: form.rateUnit === "PAISE" ? number(form.rateValue) / 100 : number(form.rateValue), minimumArea: optionalNumber(form.minimumArea), minimumCharge: optionalNumber(form.minimumCharge), bladeCharge: optionalNumber(form.bladeCharge) } : { ...formula, amount: form.baseAmount, unit: "batch" }; await mutate(row ? "PATCH" : "POST", "PRICING_RULE", { name: form.name, ruleType: form.ruleType, conditions: { ...conditions, quantity: number(form.referenceQuantity) }, priceFormula, taxRate: form.taxRate, productionTime: form.productionTime || null, sortOrder: number(form.sortOrder), taxInclusive: form.taxInclusive, isActive: form.isActive }, row ? text(row.id) : undefined); };
  return <form onSubmit={save} className={row ? "mt-3 border border-[#d7dce5] p-4" : "mt-5 border border-[#d7dce5] bg-[#f8faff] p-4"}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{input("Rule name", "name", form, update, true)}<label className="text-sm font-semibold">Rule type<select value={form.ruleType} onChange={update("ruleType")} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 font-normal">{["FIXED_PER_REFERENCE_QUANTITY", "FIXED", "PER_SQ_INCH"].map((value) => <option key={value}>{value}</option>)}</select></label>{input("Reference quantity", "referenceQuantity", form, update, true, "number")}{form.ruleType === "PER_SQ_INCH" ? <><label className="text-sm font-semibold">Rate unit<select value={form.rateUnit} onChange={update("rateUnit")} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 font-normal"><option>PAISE</option><option>RUPEES</option></select></label>{input(form.rateUnit === "PAISE" ? "Rate (paise / sq.in)" : "Rate (₹ / sq.in)", "rateValue", form, update, true, "number")}{input("Minimum area", "minimumArea", form, update, false, "number")}{input("Minimum charge (₹)", "minimumCharge", form, update, false, "number")}{input("Half-blade charge (₹)", "bladeCharge", form, update, false, "number")}</> : input("Base amount (₹, GST extra)", "baseAmount", form, update, true, "number")}{input("GST rate (%)", "taxRate", form, update, true, "number")}{input("Production time", "productionTime", form, update)}{input("Display order", "sortOrder", form, update, true, "number")}</div><div className="mt-4 flex flex-wrap items-center justify-end gap-4">{simpleCheckbox("taxInclusive", "Amount includes GST", form, setForm)}{simpleCheckbox("isActive", "Active", form, setForm)}<button className="bg-[#2457b8] px-3 py-2 text-sm font-bold text-white">{row ? "Save pricing" : "Add pricing rule"}</button>{row ? <DeleteButton onClick={() => mutate("DELETE", "PRICING_RULE", {}, text(row.id))} /> : null}</div></form>;
}

export function AddonsPanel({ rows, addons, mutate }: { rows: Row[]; addons: Row[]; mutate: CatalogMutation }) { const [form, setForm] = useState({ addonId: "", price: "0", isActive: true, isDefault: false, taxInclusive: true }); return <div><PanelTitle title="Product add-ons" description="Map a global add-on to this product and set its product-specific price." /><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); await mutate("POST", "ADDON", { ...form, sortOrder: rows.length }); setForm({ addonId: "", price: "0", isActive: true, isDefault: false, taxInclusive: true }); }}><label className="text-sm font-semibold"><span>Global add-on</span><select required value={form.addonId} onChange={(event) => setForm({ ...form, addonId: event.target.value })} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 font-normal"><option value="">Select add-on</option>{addons.filter((addon) => bool(addon.isActive)).map((addon) => <option key={text(addon.id)} value={text(addon.id)}>{text(addon.name)} ({text(addon.code)})</option>)}</select></label>{input("Product price", "price", form, (key) => (event) => setForm({ ...form, [key]: event.target.value }), true)}<div className="flex flex-wrap items-end gap-4">{simpleCheckbox("isActive", "Active", form, setForm)}{simpleCheckbox("isDefault", "Selected by default", form, setForm)}{simpleCheckbox("taxInclusive", "Tax inclusive", form, setForm)}<button className="bg-[#2457b8] px-3 py-2 text-sm font-bold text-white">Map add-on</button></div></form><div className="mt-6 space-y-3">{rows.map((item) => <AddonRow key={text((object(item.mapping) ?? item).id)} item={item} mutate={mutate} />)}</div></div>; }
function AddonRow({ item, mutate }: { item: Row; mutate: CatalogMutation }) { const mapping = object(item.mapping) ?? item; const addon = object(item.addon); const [price, setPrice] = useState(text(mapping.price)); const [active, setActive] = useState(bool(mapping.isActive)); return <article className="flex flex-col gap-3 border border-[#d7dce5] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-bold">{text(addon?.name) || "Add-on"}</p><p className="mt-1 text-xs text-[#607089]">{text(addon?.code)} · {bool(mapping.isDefault) ? "Default" : "Optional"}</p></div><input value={price} onChange={(event) => setPrice(event.target.value)} className="w-28 border border-[#c9d2df] px-3 py-2 text-sm" /><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} className="size-4 accent-[#2457b8]" />Active</label><button type="button" onClick={() => void mutate("PATCH", "ADDON", { price, isActive: active }, text(mapping.id))} className="border border-[#c9d2df] px-3 py-2 text-xs font-bold">Save</button><DeleteButton onClick={() => mutate("DELETE", "ADDON", {}, text(mapping.id))} /></article>; }

function DeliveryPanel({ rows, mutate }: { rows: Row[]; mutate: CatalogMutation }) { const [form, setForm] = useState({ deliveryMethod: "COURIER", stateCode: "GJ", price: "0", taxInclusive: false, isActive: true }); return <div><PanelTitle title="Delivery rules" description="Configure product courier charges for Gujarat and Rajasthan. Pickup uses the all-state code." /><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); await mutate("POST", "DELIVERY_RULE", { ...form, sortOrder: rows.length }); setForm({ deliveryMethod: "COURIER", stateCode: "GJ", price: "0", taxInclusive: false, isActive: true }); }}><label className="text-sm font-semibold"><span>Method</span><select value={form.deliveryMethod} onChange={(event) => setForm({ ...form, deliveryMethod: event.target.value, stateCode: event.target.value === "PICKUP" ? "*" : form.stateCode === "*" ? "GJ" : form.stateCode })} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 font-normal"><option>PICKUP</option><option>COURIER</option></select></label><StateSelect value={form.stateCode} onChange={(stateCode) => setForm({ ...form, stateCode })} />{input("Charge (₹, GST extra)", "price", form, (key) => (event) => setForm({ ...form, [key]: event.target.value }), true)}<div className="flex flex-wrap items-end gap-4">{simpleCheckbox("taxInclusive", "Charge includes GST", form, setForm)}{simpleCheckbox("isActive", "Active", form, setForm)}<button className="bg-[#2457b8] px-3 py-2 text-sm font-bold text-white">Add rule</button></div></form><div className="mt-6 space-y-3">{rows.map((row) => <DeliveryRow key={text(row.id)} row={row} mutate={mutate} />)}</div></div>; }
function DeliveryRow({ row, mutate }: { row: Row; mutate: CatalogMutation }) { const [price, setPrice] = useState(text(row.price)); const [stateCode, setStateCode] = useState(text(row.stateCode)); return <article className="flex flex-col gap-3 border border-[#d7dce5] p-4 sm:flex-row sm:items-center"><p className="w-32 font-bold">{text(row.deliveryMethod)}</p><StateSelect value={stateCode} onChange={setStateCode} /><input value={price} onChange={(event) => setPrice(event.target.value)} className="w-28 border border-[#c9d2df] px-3 py-2 text-sm" /><p className="text-sm text-[#607089]">{formattedAmount(price)}{bool(row.taxInclusive) ? " incl. tax" : " + GST"}</p><div className="ml-auto flex gap-2"><button type="button" onClick={() => void mutate("PATCH", "DELIVERY_RULE", { stateCode, price }, text(row.id))} className="border border-[#c9d2df] px-3 py-2 text-xs font-bold">Save</button><DeleteButton onClick={() => mutate("DELETE", "DELIVERY_RULE", {}, text(row.id))} /></div></article>; }
function StateSelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="text-sm font-semibold">State<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full min-w-40 border border-[#c9d2df] px-3 py-2.5 font-normal"><option value="*">All / Pickup (*)</option><option value="GJ">Gujarat (GJ)</option><option value="RJ">Rajasthan (RJ)</option></select></label>; }

function LocationSurchargesPanel({ rows, pricingRules, mutate }: { rows: Row[]; pricingRules: Row[]; mutate: CatalogMutation }) {
  const [form, setForm] = useState({ pricingRuleId: "", locationScope: "OUTSIDE_CITY", city: "Ahmedabad", stateCode: "GJ", amount: "0", taxInclusive: true, isActive: true });
  return <div><PanelTitle title="Customer location surcharges" description="Add product or configuration charges based on the city/state saved in the signed-in customer profile." />
    <form className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3" onSubmit={async (event) => { event.preventDefault(); await mutate("POST", "LOCATION_SURCHARGE", { ...form, pricingRuleId: form.pricingRuleId || null, city: form.city || null, stateCode: form.stateCode || null, sortOrder: rows.length }); setForm({ pricingRuleId: "", locationScope: "OUTSIDE_CITY", city: "Ahmedabad", stateCode: "GJ", amount: "0", taxInclusive: true, isActive: true }); }}>
      <label className="text-sm font-semibold">Configuration<select value={form.pricingRuleId} onChange={(event) => setForm({ ...form, pricingRuleId: event.target.value })} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 font-normal"><option value="">All configurations</option>{pricingRules.map((rule) => <option key={text(rule.id)} value={text(rule.id)}>{text(rule.name)}</option>)}</select></label>
      <label className="text-sm font-semibold">Scope<select value={form.locationScope} onChange={(event) => setForm({ ...form, locationScope: event.target.value })} className="mt-1.5 w-full border border-[#c9d2df] px-3 py-2.5 font-normal">{["CITY", "OUTSIDE_CITY", "STATE", "OUTSIDE_STATE"].map((scope) => <option key={scope}>{scope}</option>)}</select></label>
      {input("City", "city", form, (key) => (event) => setForm({ ...form, [key]: event.target.value }), true)}
      {input("State code", "stateCode", form, (key) => (event) => setForm({ ...form, [key]: event.target.value.toUpperCase() }), true)}
      {input("Charge", "amount", form, (key) => (event) => setForm({ ...form, [key]: event.target.value }), true)}
      <div className="flex items-end gap-3">{simpleCheckbox("taxInclusive", "Tax inclusive", form, setForm)}<button className="bg-[#2457b8] px-3 py-2.5 text-sm font-bold text-white">Add surcharge</button></div>
    </form>
    <div className="mt-5 space-y-2">{rows.map((row) => <div key={text(row.id)} className="flex flex-wrap items-center gap-3 border border-[#d7dce5] p-3 text-sm"><strong>{text(row.locationScope).replaceAll("_", " ")}</strong><span>{text(row.city) || text(row.stateCode) || "Any location"}</span><span>{formattedAmount(row.amount)}</span><span className="text-[#607089]">{pricingRules.find((rule) => text(rule.id) === text(row.pricingRuleId))?.name ? text(pricingRules.find((rule) => text(rule.id) === text(row.pricingRuleId))?.name) : "All configurations"}</span><DeleteButton onClick={() => mutate("DELETE", "LOCATION_SURCHARGE", {}, text(row.id))} /></div>)}</div>
  </div>;
}

export function ArtworkPanel({ product, onSave }: { product: Row | null; onSave: (data: Row) => Promise<void> }) { const [required, setRequired] = useState(bool(product?.artworkRequired)); const [instructions, setInstructions] = useState(text(product?.artworkInstructions)); const [saving, setSaving] = useState(false); return <div><PanelTitle title="Artwork requirements" description="Set clear CDR instructions before customers reach payment or request a quote." /><div className="mt-6 max-w-2xl"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={required} onChange={(event) => setRequired(event.target.checked)} className="size-4 accent-[#2457b8]" />Require artwork before production</label><label className="mt-4 block text-sm font-semibold">Artwork instructions<textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} rows={6} className="mt-1.5 w-full border border-[#c9d2df] p-3 text-sm font-normal" /></label><button type="button" disabled={saving} onClick={async () => { setSaving(true); try { await onSave({ artworkRequired: required, artworkInstructions: instructions || undefined }); } finally { setSaving(false); } }} className="mt-4 inline-flex items-center gap-2 bg-[#2457b8] px-4 py-2.5 text-sm font-bold text-white"><Check size={16} />{saving ? "Saving..." : "Save artwork settings"}</button><p className="mt-4 text-xs leading-5 text-[#607089]">Customer artwork is reviewed from the Artwork workspace. Uploading binary CDR files needs a configured object-storage upload provider and is not simulated here.</p></div></div>; }

type CatalogMutation = (method: "POST" | "PATCH" | "DELETE", resource: string, data?: Row, resourceId?: string) => Promise<void>;
function array(value: unknown) { return Array.isArray(value) ? value as Row[] : []; }
function object(value: unknown) { return value && typeof value === "object" ? value as Row : null; }
function empty(value: string) { return value.trim() ? value.trim() : undefined; }
function productForm(product: Row | null) { return { categoryId: text(product?.categoryId), name: text(product?.name), slug: text(product?.slug), description: text(product?.description), shortDescription: text(product?.shortDescription), productCode: text(product?.productCode), productReference: text(product?.productReference), productClass: text(product?.productClass), productType: text(product?.productType) || "CONFIGURABLE", configuration: json(product?.configuration), status: text(product?.status) || "ACTIVE", orderable: bool(product?.orderable), quoteable: bool(product?.quoteable, true), isActive: bool(product?.isActive, true), productionTime: text(product?.productionTime), artworkRequired: bool(product?.artworkRequired), artworkInstructions: text(product?.artworkInstructions), sortOrder: text(product?.sortOrder) || "0", referenceQuantity: text(product?.referenceQuantity), referenceWeight: text(product?.referenceWeight), referenceWeightUnit: text(product?.referenceWeightUnit), pricesTaxInclusive: bool(product?.pricesTaxInclusive, true) }; }
function input(label: string, key: string, form: Record<string, unknown>, update: (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => void, required = false, type = "text", placeholder?: string) { return <label className="block text-sm font-semibold text-[#263753]"><span>{label}</span><input type={type} required={required} value={text(form[key])} onChange={update(key)} placeholder={placeholder} className="mt-1.5 w-full border border-[#c9d2df] bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-[#2457b8]" /></label>; }
function textarea(label: string, key: string, form: Record<string, unknown>, update: (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => void, rows = 4) { return <label className="block text-sm font-semibold text-[#263753]"><span>{label}</span><textarea value={text(form[key])} onChange={update(key)} rows={rows} className="mt-1.5 w-full border border-[#c9d2df] bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-[#2457b8]" /></label>; }
function checkbox(key: string, label: string, form: Record<string, unknown>, update: (key: string) => (event: React.ChangeEvent<HTMLInputElement>) => void) { return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={bool(form[key])} onChange={update(key)} className="size-4 accent-[#2457b8]" />{label}</label>; }
function simpleCheckbox<T extends object>(key: keyof T & string, label: string, form: T, setForm: React.Dispatch<React.SetStateAction<T>>) { return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={bool(form[key])} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.checked }) as T)} className="size-4 accent-[#2457b8]" />{label}</label>; }
function PanelTitle({ title, description }: { title: string; description: string }) { return <div className="border-b border-[#e4e8ef] pb-4"><h2 className="font-bold text-[#162237]">{title}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[#607089]">{description}</p></div>; }
function SaveButton({ saving }: { saving: boolean }) { return <button disabled={saving} className="mt-6 inline-flex items-center gap-2 bg-[#2457b8] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><Check size={16} />{saving ? "Saving..." : "Save product"}</button>; }
function DeleteButton({ onClick }: { onClick: () => Promise<void> }) { return <button type="button" onClick={() => { if (window.confirm("Delete this record?")) void onClick(); }} className="border border-[#efc4be] p-2 text-[#b13a2f]" aria-label="Delete"><Trash2 size={15} /></button>; }
function Message({ tone, children, onDismiss }: { tone: "success" | "error"; children: React.ReactNode; onDismiss?: () => void }) { return <div className={`mt-5 flex justify-between gap-3 border p-3 text-sm ${tone === "success" ? "border-[#bbdfc9] bg-[#f3fbf5] text-[#1e6b3a]" : "border-[#efc4be] bg-[#fff6f4] text-[#a9362c]"}`}><span className="flex gap-2"><CircleAlert size={17} className="mt-0.5 shrink-0" />{children}</span>{onDismiss ? <button type="button" onClick={onDismiss}><X size={16} /></button> : null}</div>; }
function Status({ value, active }: { value: string; active: boolean }) { return <span className={`inline-flex px-2 py-1 text-xs font-bold ${active && value === "ACTIVE" ? "bg-[#edf7f0] text-[#237546]" : "bg-[#f5f1ed] text-[#755c4c]"}`}>{value || "DRAFT"}</span>; }
