"use client";

import Link from "next/link";
import { ArrowRight, Check, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";

type Item = { id: string; productId: string; quantity: number; configuration: Record<string, string>; product: { name: string } };

export function QuoteFlow() {
  const [items, setItems] = useState<Item[]>([]); const [form, setForm] = useState({ contactName: "", email: "", phone: "", companyName: "", notes: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [quoteNumber, setQuoteNumber] = useState("");
  useEffect(() => { async function load() { try { const response = await fetch("/api/cart?kind=QUOTE", { cache: "no-store" }); const payload = await response.json(); if (response.status === 401) throw new Error("Sign in to view your quote basket."); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Could not load your quote basket"); setItems(payload.data.items); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load your quote basket"); } finally { setLoading(false); } } void load(); }, []);
  async function remove(id: string) { const response = await fetch(`/api/cart/items/${id}`, { method: "DELETE" }); if (response.ok) setItems((current) => current.filter((item) => item.id !== id)); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); try { const response = await fetch("/api/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, items: items.map((item) => ({ productId: item.productId, description: item.product.name, configuration: item.configuration, quantity: item.quantity, unitPrice: "0" })) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "We could not submit your request."); await fetch("/api/cart?kind=QUOTE", { method: "DELETE" }); setQuoteNumber(payload.data.quoteNumber); } catch (caught) { setError(caught instanceof Error ? caught.message : "We could not submit your request."); } }
  if (quoteNumber) return <div className="mx-auto max-w-xl py-20 text-center"><Check className="mx-auto text-[#8b2f24]" size={42} /><p className="mt-5 text-sm font-bold">Quote request {quoteNumber} received.</p><Link href="/account" className="mt-6 inline-flex items-center gap-2 bg-[#17221c] px-5 py-3 text-sm font-bold text-white">View your account <ArrowRight size={16} /></Link></div>;
  return <div className="grid gap-8 py-8 xl:grid-cols-[1fr_380px]"><section><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#f15a3a]">Your brief</p><h1 className="mt-2 text-3xl font-bold">Request a quote</h1><div className="mt-6 space-y-3">{loading ? <p className="text-sm text-[#646b64]">Loading quote basket...</p> : items.length ? items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 border border-[#ddd9d0] bg-white p-4"><div><p className="font-bold">{item.product.name}</p><p className="mt-1 text-xs text-[#777d76]">Qty {item.quantity}</p></div><button type="button" onClick={() => void remove(item.id)} className="text-[#8b2f24]" aria-label={`Remove ${item.product.name}`}><Trash2 size={17} /></button></div>) : <div className="border border-dashed border-[#cfcfc6] bg-white p-6"><p className="font-bold">No quote items selected yet.</p><Link href="/catalog" className="mt-3 inline-flex gap-2 text-sm font-bold text-[#f15a3a]">Browse catalogue <ArrowRight size={15} /></Link></div>}</div></section><form onSubmit={submit} className="h-fit border border-[#d9d6ce] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.14em]">Contact details</p><div className="mt-4 space-y-3">{[["contactName", "Your name", "text"], ["email", "Work email", "email"], ["phone", "Phone number", "tel"], ["companyName", "Company name", "text"]].map(([key, label, type]) => <label key={key} className="block"><span className="mb-2 block text-xs font-bold">{label}</span><input required={key === "contactName" || key === "email"} type={type} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="w-full border border-[#d9d6ce] bg-[#fbfaf7] px-3 py-3 text-sm outline-none" /></label>)}<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Requirements and deadline" className="w-full border border-[#d9d6ce] bg-[#fbfaf7] px-3 py-3 text-sm outline-none" rows={4} /></div>{error ? <p className="mt-4 text-sm text-[#8b2f24]">{error}</p> : null}<button disabled={!items.length} className="mt-5 flex w-full items-center justify-center gap-2 bg-[#17221c] px-4 py-3.5 text-sm font-bold text-white disabled:opacity-50">Send request <ArrowRight size={16} /></button></form></div>;
}
