import Link from "next/link";
import { Mail, MapPin, Phone } from "lucide-react";

export function StorefrontFooter() {
  return <footer className="border-t border-[#173565] bg-[var(--mc-navy)] text-[#dbe7ff]">
    <div className="mx-auto grid max-w-[1440px] gap-9 px-4 py-10 sm:grid-cols-2 lg:grid-cols-[1.35fr_.8fr_.8fr_1.2fr] lg:px-8">
      <div><p className="text-lg font-bold text-white">Mahavir Card</p><p className="mt-3 max-w-xs text-[15px] leading-6 text-[#b7c7e5]">All kind printing solutions for businesses, from everyday cards to packaging and bulk commercial work.</p><p className="mt-5 text-[13px] font-semibold uppercase tracking-[0.12em] text-[#8fb4ff]">Offset printing {"\u00b7"} Ahmedabad</p></div>
      <div><p className="text-[13px] font-bold uppercase tracking-[0.12em] text-white">Products</p><div className="mt-4 space-y-3 text-[15px] text-[#b7c7e5]"><Link className="block hover:text-white" href="/products?category=business-cards">Business cards</Link><Link className="block hover:text-white" href="/products?category=printing">Printing</Link><Link className="block hover:text-white" href="/products?category=packaging">Packaging</Link><Link className="block hover:text-white" href="/products?category=labels-stickers">Labels</Link><Link className="block hover:text-white" href="/products?category=stationery">Stationery</Link></div></div>
      <div><p className="text-[13px] font-bold uppercase tracking-[0.12em] text-white">Support</p><div className="mt-4 space-y-3 text-[15px] text-[#b7c7e5]"><Link className="block hover:text-white" href="/quote">Request a quote</Link><Link className="block hover:text-white" href="/account">Orders</Link><a className="block hover:text-white" href="#contact">Contact</a></div></div>
      <div id="contact"><p className="text-[13px] font-bold uppercase tracking-[0.12em] text-white">Contact</p><div className="mt-4 space-y-3 text-[15px] leading-6 text-[#b7c7e5]"><p className="flex items-start gap-3"><MapPin size={16} className="mt-1 shrink-0 text-[#8fb4ff]" />Khadia Golwad, Opp. Jain Digamber Mandir, Ahmedabad - 01</p><a className="flex items-center gap-3 hover:text-white" href="tel:+919426371150"><Phone size={16} className="shrink-0 text-[#8fb4ff]" />+91 94263 71150</a><a className="flex items-center gap-3 break-all hover:text-white" href="mailto:mahavircard2011@gmail.com"><Mail size={16} className="shrink-0 text-[#8fb4ff]" />mahavircard2011@gmail.com</a></div></div>
    </div>
    <div className="border-t border-white/10"><div className="mx-auto flex max-w-[1440px] flex-col gap-2 px-4 py-4 text-[13px] text-[#8fa2c4] sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>Mahavir Card {"\u00b7"} Ahmedabad commercial printing</p><p>Prices shown online include applicable taxes where configured.</p></div></div>
  </footer>;
}
